### ISSUE TITLE
Gif for EasyTipCalculator App

### ISSUE THREAD

**Issue by tugcekeser** [tugcekeser/EasyTipCalculator#1]
![demo_codepath_tippy](https://cloud.githubusercontent.com/assets/17666583/23628157/50697406-0268-11e7-8f64-37be2f4f3e99.gif)

**Comment by codepathreview** [comment]
Hello Rabia,

Great work!! This exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer learn the practical elements of iOS development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

Great to see you were able to complete a large number of optional features to your app already. Your project looks great. As you can probably tell, the optional features available on each project are a great vehicle for exploring the iOS framework deeper.

We'll be following up with you again shortly to outline the next steps in the admissions process.
